### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by julien-f** [vatesfr/xo-server-backup-reports#1]
- [x] `String()` instead of `toString()`
- [x] Simplify joins as much as possible
- [x] Fix indentation
- [x] Description in configuration schema
- [x] Fill up the `package.json`
- [x] Fill the README
- [x] `vm.uuid` instead of `call.params.id`
- [x] Remove error handling from `this._xo.sendEmail(...)`

**Comment by olivierlambert** [comment]
Also:

* [ ] Github repo description.
